[
  ./minecraft/build/distribution.nix
  ./minecraft/build/minecraft-nix.nix
  ./minecraft/game/version.nix
  ./minecraft/server/eula.nix
  ./minecraft/build.nix
  ./minecraft/files.nix
  ./minecraft/launch-script.nix
  ./minecraft/items.nix
  ./misc/lock.nix
  ./misc/name.nix
  ./misc/update.nix
]
